name:  "Issue Report"
description: "Report identified issues"
body : 
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Describe the issue
    validations: 
      required: true
  - type: input
    id: contact
    attributes: 
      label: Contact Details 
      description: How can we get in touch with you if we need more info
    validations:
      required: false 
